//! Process configuration. Decode fixed-size public identifiers exactly once at startup.
//!
//! Required environment variables:
//! - LASTRO_API_BIND, e.g. `127.0.0.1:8080`;
//! - LASTRO_DATABASE_URL;
//! - LASTRO_AGENT_TOKEN (demo transport authentication; secret, never logged);
//! - LASTRO_SOLANA_RPC_URL;
//! - LASTRO_DEPLOYMENT_ID_HEX (32 bytes / 64 lowercase hex chars);
//! - LASTRO_STATION_PUBKEY_HEX (SEC1 compressed P-256, 33 bytes / 66 lowercase hex chars);
//! - LASTRO_PROGRAM_ID (base58 Solana address generated by the real program keypair).
//!
//! Optional:
//! - LASTRO_OPERATOR_TOKEN (>= 32 chars) enables the operational v2 routes;
//! - LASTRO_PRIORITY_FEE_MICRO_LAMPORTS, compute-unit price appended to prepared transactions
//!   (max 1_000_000); unset keeps the exact two-instruction envelope;
//! - LASTRO_CORS_ALLOWED_ORIGINS, comma-separated `scheme://host[:port]` origins. Unset keeps
//!   the permissive development policy; public deployments must set it.
//!
//! No default may silently point execution at the wrong deployment.

use std::{env, net::SocketAddr, str::FromStr};

use axum::http::HeaderValue;

use lastro_protocol::{crypto::derive_station_id, ids::DeploymentId};
use solana_pubkey::Pubkey;

use crate::error::ApiError;

#[derive(Clone)]
pub struct AppConfig {
    pub bind_addr: SocketAddr,
    pub database_url: String,
    pub agent_token: String,
    pub operator_token: Option<String>,
    pub solana_rpc_url: String,
    pub deployment_id: DeploymentId,
    pub station_pubkey33: [u8; 33],
    pub lastro_program_id: String,
    /// Empty means any origin (development only).
    pub cors_allowed_origins: Vec<HeaderValue>,
    pub priority_fee_micro_lamports: Option<u64>,
}

impl AppConfig {
    pub fn from_env() -> Result<Self, ApiError> {
        Self::from_lookup(|name| env::var(name).ok())
    }

    pub fn from_lookup<F>(mut lookup: F) -> Result<Self, ApiError>
    where
        F: FnMut(&str) -> Option<String>,
    {
        fn required<F>(lookup: &mut F, name: &'static str) -> Result<String, ApiError>
        where
            F: FnMut(&str) -> Option<String>,
        {
            let value = lookup(name).ok_or_else(|| ApiError::Config(format!("missing {name}")))?;
            if value.trim().is_empty() {
                return Err(ApiError::Config(format!("{name} must not be empty")));
            }
            Ok(value)
        }

        fn hex_array<const N: usize>(name: &'static str, value: &str) -> Result<[u8; N], ApiError> {
            if value.len() != N * 2 || value != value.to_ascii_lowercase() {
                return Err(ApiError::Config(format!(
                    "{name} must be exactly {N} bytes of lowercase hexadecimal"
                )));
            }
            let bytes = hex::decode(value).map_err(|_| {
                ApiError::Config(format!("{name} must be valid lowercase hexadecimal"))
            })?;
            bytes
                .try_into()
                .map_err(|_| ApiError::Config(format!("{name} must decode to exactly {N} bytes")))
        }

        let bind_addr = required(&mut lookup, "LASTRO_API_BIND")?
            .parse()
            .map_err(|_| ApiError::Config("LASTRO_API_BIND must be a socket address".into()))?;

        let database_url = required(&mut lookup, "LASTRO_DATABASE_URL")?;
        if !(database_url.starts_with("postgres://") || database_url.starts_with("postgresql://")) {
            return Err(ApiError::Config(
                "LASTRO_DATABASE_URL must use postgres:// or postgresql://".into(),
            ));
        }

        let agent_token = required(&mut lookup, "LASTRO_AGENT_TOKEN")?;
        if agent_token.len() < 32 {
            return Err(ApiError::Config(
                "LASTRO_AGENT_TOKEN must contain at least 32 characters".into(),
            ));
        }

        let operator_token =
            lookup("LASTRO_OPERATOR_TOKEN").filter(|value| !value.trim().is_empty());
        if operator_token
            .as_ref()
            .is_some_and(|value| value.len() < 32)
        {
            return Err(ApiError::Config(
                "LASTRO_OPERATOR_TOKEN must contain at least 32 characters".into(),
            ));
        }

        let solana_rpc_url = required(&mut lookup, "LASTRO_SOLANA_RPC_URL")?;
        let parsed_rpc = reqwest::Url::parse(&solana_rpc_url).map_err(|_| {
            ApiError::Config("LASTRO_SOLANA_RPC_URL must be an absolute http(s) URL".into())
        })?;
        if !matches!(parsed_rpc.scheme(), "http" | "https") {
            return Err(ApiError::Config(
                "LASTRO_SOLANA_RPC_URL must use http or https".into(),
            ));
        }

        let deployment_id = hex_array::<32>(
            "LASTRO_DEPLOYMENT_ID_HEX",
            &required(&mut lookup, "LASTRO_DEPLOYMENT_ID_HEX")?,
        )?;
        let station_pubkey33 = hex_array::<33>(
            "LASTRO_STATION_PUBKEY_HEX",
            &required(&mut lookup, "LASTRO_STATION_PUBKEY_HEX")?,
        )?;
        derive_station_id(&station_pubkey33).map_err(|_| {
            ApiError::Config(
                "LASTRO_STATION_PUBKEY_HEX must be a valid compressed P-256 public key".into(),
            )
        })?;

        let lastro_program_id = required(&mut lookup, "LASTRO_PROGRAM_ID")?;
        Pubkey::from_str(&lastro_program_id).map_err(|_| {
            ApiError::Config("LASTRO_PROGRAM_ID must be a valid Solana address".into())
        })?;

        let cors_allowed_origins = lookup("LASTRO_CORS_ALLOWED_ORIGINS")
            .map(|value| parse_origins(&value))
            .transpose()?
            .unwrap_or_default();

        let priority_fee_micro_lamports = lookup("LASTRO_PRIORITY_FEE_MICRO_LAMPORTS")
            .filter(|value| !value.trim().is_empty())
            .map(|value| {
                value
                    .parse::<u64>()
                    .ok()
                    .filter(|price| (1..=MAX_PRIORITY_FEE_MICRO_LAMPORTS).contains(price))
                    .ok_or_else(|| {
                        ApiError::Config(format!(
                            "LASTRO_PRIORITY_FEE_MICRO_LAMPORTS must be an integer in 1..={MAX_PRIORITY_FEE_MICRO_LAMPORTS}"
                        ))
                    })
            })
            .transpose()?;

        Ok(Self {
            bind_addr,
            database_url,
            agent_token,
            operator_token,
            solana_rpc_url,
            deployment_id,
            station_pubkey33,
            lastro_program_id,
            cors_allowed_origins,
            priority_fee_micro_lamports,
        })
    }
}

/// Priority fee = 200_000 units x price / 1_000_000. This cap bounds it to 200_000 lamports
/// (0.0002 SOL) per transaction, the same bound the browser enforces before signing.
pub const MAX_PRIORITY_FEE_MICRO_LAMPORTS: u64 = 1_000_000;

/// Accepts only bare origins so a typo cannot silently widen or break the CORS policy.
fn parse_origins(value: &str) -> Result<Vec<HeaderValue>, ApiError> {
    let invalid = || {
        ApiError::Config(
            "LASTRO_CORS_ALLOWED_ORIGINS must list http(s) origins without paths".into(),
        )
    };
    value
        .split(',')
        .map(str::trim)
        .filter(|origin| !origin.is_empty())
        .map(|origin| {
            let url = reqwest::Url::parse(origin).map_err(|_| invalid())?;
            if !matches!(url.scheme(), "http" | "https")
                || url.host_str().is_none()
                || url.path() != "/"
                || origin.ends_with('/')
                || url.query().is_some()
                || url.fragment().is_some()
            {
                return Err(invalid());
            }
            HeaderValue::from_str(origin).map_err(|_| invalid())
        })
        .collect()
}
